"""The stable error and exit vocabulary the CLI publishes to shells and agents.

Every value here is a public contract: a shipped code string may not be reworded and a
shipped exit number may not be reassigned. Prose belongs to the `CliError` subclasses in
`failures.py`, so automation branches on identity while messages keep improving.

Several codes deliberately share one exit status — statuses are coarse shell signals, codes
are precise machine semantics.
"""

from __future__ import annotations

from enum import IntEnum, StrEnum


class CliErrorCode(StrEnum):
    """Stable failure identity for users and automation."""

    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    CREDIT_EXHAUSTED = "CREDIT_EXHAUSTED"
    API_UNAVAILABLE = "API_UNAVAILABLE"
    API_PROTOCOL_ERROR = "API_PROTOCOL_ERROR"
    CONFIG_INVALID = "CONFIG_INVALID"
    CONFIG_WRITE_CONFLICT = "CONFIG_WRITE_CONFLICT"
    CREDENTIAL_STORE_UNAVAILABLE = "CREDENTIAL_STORE_UNAVAILABLE"
    OPERATION_FAILED = "OPERATION_FAILED"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    INTERRUPTED = "INTERRUPTED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    CONNECTION_CONFIGURATION_INVALID = "CONNECTION_CONFIGURATION_INVALID"
    CONNECTION_OAUTH_FAILED = "CONNECTION_OAUTH_FAILED"
    CONNECTION_OAUTH_STATE_INVALID = "CONNECTION_OAUTH_STATE_INVALID"
    CONNECTION_AUTH_REQUIRED = "CONNECTION_AUTH_REQUIRED"
    CONNECTION_REAUTH_REQUIRED = "CONNECTION_REAUTH_REQUIRED"
    CONNECTION_SCOPE_INSUFFICIENT = "CONNECTION_SCOPE_INSUFFICIENT"
    CONNECTION_RESOURCE_UNAVAILABLE = "CONNECTION_RESOURCE_UNAVAILABLE"
    CONNECTION_PROTOCOL_ERROR = "CONNECTION_PROTOCOL_ERROR"
    CONNECTION_API_UNAVAILABLE = "CONNECTION_API_UNAVAILABLE"
    CONNECTION_RATE_LIMITED = "CONNECTION_RATE_LIMITED"
    CONNECTION_STORE_UNAVAILABLE = "CONNECTION_STORE_UNAVAILABLE"
    CONNECTION_NOT_FOUND = "CONNECTION_NOT_FOUND"


class ExitCode(IntEnum):
    """Stable shell statuses documented by the CLI."""

    SUCCESS = 0
    OPERATIONAL_FAILURE = 1
    USAGE = 2
    PARTIAL_OUTCOME = 3
    AUTHENTICATION = 4
    CREDIT_EXHAUSTED = 5
    SOFTWARE = 70
    INTERRUPTED = 130
